sudo: false
language: erlang
otp_release:
  - 19.1
  - 18.3
  - 17.5
  - R16B03-1
before_script:
  - wget https://s3-us-west-2.amazonaws.com/rebar3-canary/canary/rebar3
  - chmod u+x rebar3
script: "make travis"
